CREATE TABLE [dbo].[Client]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [MobilePhone] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(128) NOT NULL
)
